### PR TITLE
Fixed DerelictGL3.reload not using MissingSymbolCallback

### PR DESCRIPTION
**Pull request by ParticlePeter**
Forwarded MissingSymbolCallback from gl3 module to internal module

### CODE REVIEW

**Comment by ParticlePeter** [comment]
Hi Aldacron, I have no Idea why github merged these two pull requests, they are not related.
Comment to the second one: the two GLenums I changed are according to the glcorearb.h header.

**Comment by mathstuf** [comment]
It "merged" them because both are on your master branch. A PR offers to merge all commits on the branch you want merged which aren't on the target branch. Use a topic branch and resubmit if you want them split (I don't think you can change the source branch in a PR).

**Comment by aldacron** [comment]
There's nothing here to "fix", IMO. Like I said in a previous comment, this is as it should be. It was an intentional design decision made long, long ago. The purpose of the missing symbol callback is to allow loading of older versions of a library with a binding to a newer version. This is already supported in DerelictGL3.reload with the minVersion and maxVersion parameters.

The problem you are having is one that was unforeseen: a driver is reporting that it supports a specific version of OpenGL, but one or more of the functions required by that version is missing. IMO, this means that the advertised OpenGL version is not actually available. If any "fix" on the Derelict side is required, it should be that the loader should detect this and do one of two things: if the problematic version was not specified as the minVersion, downgrade the available version; otherwise, throw the exception. I don't think it's a good idea to ignore the exception and continue loading in this case, as there could be consequences with extensions which are dependent on specific OpenGL versions.

I don't know if this is a driver bug in that the functions are completely missing, or if it's something with their implementation that prevents them from being loaded through the normal process. Either way, it is a driver bug. I'm not sure we should be changing Derelict's behavior to work around it.

**Comment by ParticlePeter** [comment]
Uh, I think I misunderstood your comment in issue #43, I understood that reload should also go through the missingSymbolCallback. So what is with the other symbols from GL 4.5 which are available in my driver, do they get loaded when I use context version 4.4?
I did report a Driver Bug to AMD by the way.

Actually there IS something which should be fixed, the second commit which I submitted. Module arb has 2 ill named symbols in it. Please compare to glcorearb.h Header.

**Comment by aldacron** [comment]
> So what is with the other symbols from GL 4.5 which are available in my driver, do they get loaded when I use context version 4.4?

Many of the 3.x - 4.x functions are implemented as part of ARB extensions, even though they don't have the ARB suffix. So those 4.5 functions that are available in extensions should still be loaded. If you look at the source [where 4.5 is loaded](https://github.com/DerelictOrg/DerelictGL3/blob/master/source/derelict/opengl3/gl3.d#L425), you'll see that is everything except the glGetn* functions.

>  there IS something which should be fixed

Yes, I saw that. I was referring specifically to the missing symbol stuff. I'll fix the enums soonish. I'll keep this open as a reminder.

**Comment by ParticlePeter** [comment]
Thanks for clarification. Refering your example, I inspected the link. What would happen, if my driver would expose "glGetnCompressedTexImage" but not "glGetnTexImage". As far as I can see loading procedure would still throw and I would not be able to access the other available core functions, right?

I agree that this is a driver bug and in this case amd should react asap, but well they don't. I reported another bug some time ago without reaction.

In any case, I'll use GL 4.4 for now

**Comment by aldacron** [comment]
> What would happen, if my driver would expose "glGetnCompressedTexImage" but not "glGetnTexImage". As far as I can see loading procedure would still throw and I would not be able to access the other available core functions, right?

Everything loaded before glGetnTexImage would be available, everything after would not. The latter actually includes all supported extensions, as they are loaded after the core stuff. That's why defaulting to 4.4 is the safest bet.

What you could do is try to load 4.5 and if an exception is thrown, catch it and call reload again with 4.4 set as the minimum version. This will allow you to use 4.5 where available on non-buggy drivers and fall back to 4.4, while still loading the extensions, where the driver bug is present. Just keep in mind that 4.5 may simply not be supported, in which case no exception is thrown, so you should always test the loaded version to determine if it is. In other words, don't set a flag when you catch the exception.

**Comment by aldacron** [comment]
FYI, I've tagged a new release that contains the fix for the misspelled enums.

**Pull request closed without merging**
